<?php

/**
 * BaseObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $number
 * @property text $description
 * @property varchar $name
 * @property varchar $origin
 * @property varchar $date
 * @property varchar $img_link
 * @property varchar $origin_link
 * @property varchar $wp_link
 * @property varchar $bbc_link
 * @property varchar $bm_link
 * @property varchar $audio_link
 * @property varchar $transcript
 * @property varchar $floor
 * @property varchar $room
 * 
 * @method integer getNumber()      Returns the current record's "number" value
 * @method text    getDescription() Returns the current record's "description" value
 * @method varchar getName()        Returns the current record's "name" value
 * @method varchar getOrigin()      Returns the current record's "origin" value
 * @method varchar getDate()        Returns the current record's "date" value
 * @method varchar getImgLink()     Returns the current record's "img_link" value
 * @method varchar getOriginLink()  Returns the current record's "origin_link" value
 * @method varchar getWpLink()      Returns the current record's "wp_link" value
 * @method varchar getBbcLink()     Returns the current record's "bbc_link" value
 * @method varchar getBmLink()      Returns the current record's "bm_link" value
 * @method varchar getAudioLink()   Returns the current record's "audio_link" value
 * @method varchar getTranscript()  Returns the current record's "transcript" value
 * @method varchar getFloor()       Returns the current record's "floor" value
 * @method varchar getRoom()        Returns the current record's "room" value
 * @method Object  setNumber()      Sets the current record's "number" value
 * @method Object  setDescription() Sets the current record's "description" value
 * @method Object  setName()        Sets the current record's "name" value
 * @method Object  setOrigin()      Sets the current record's "origin" value
 * @method Object  setDate()        Sets the current record's "date" value
 * @method Object  setImgLink()     Sets the current record's "img_link" value
 * @method Object  setOriginLink()  Sets the current record's "origin_link" value
 * @method Object  setWpLink()      Sets the current record's "wp_link" value
 * @method Object  setBbcLink()     Sets the current record's "bbc_link" value
 * @method Object  setBmLink()      Sets the current record's "bm_link" value
 * @method Object  setAudioLink()   Sets the current record's "audio_link" value
 * @method Object  setTranscript()  Sets the current record's "transcript" value
 * @method Object  setFloor()       Sets the current record's "floor" value
 * @method Object  setRoom()        Sets the current record's "room" value
 * 
 * @package    hotw100
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('object');
        $this->hasColumn('number', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('name', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('origin', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('date', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('img_link', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('origin_link', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('wp_link', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('bbc_link', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('bm_link', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('audio_link', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('transcript', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('floor', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('room', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}