all:
    javascripts: [http://code.jquery.com/jquery-1.4.4.min.js, http://code.jquery.com/mobile/1.0a2/jquery.mobile-1.0a2.min.js]
    stylesheets: [http://code.jquery.com/mobile/1.0a2/jquery.mobile-1.0a2.min.css]
