<?php

/**
 * ObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Object');
    }
}