generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Object
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          object
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [_image, =number, =name, origin, date]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
