<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('object', 'origin_link', 'varchar', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('object', 'origin_link');
    }
}